
# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      boolean:
        type: boolean
        description: True or False
      deploymentType:
        type: choice
        description : Input DeploymentType
        options:
          - applicationSecurityGroups
          - networkSecurityGroups
          - privateEndpoints
          - resourceGroups
          - routeTables
          - networkCore
          - management
          - security
          - identity
          - loadBalancers
          - vms
          - all
      stringInput:
        description: input value
    
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
      
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      test1: ${{ inputs.boolean}}
      test2: ${{ inputs.deploymentType}}
    steps:
      - name: list out envs
        run:   |
          write-host ${{ $test1 }}
          write-host ${{test2}
          write-host ${{env.DAY_OF_WEEK}}
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: show github workspace files 
        run: |
          ls ${{$github_workspace}} 
      - name: Upload artifact 1
        uses: actions/upload-artifact@v4
        with:
          name: infrastructure1
          path: './'
          include-hidden-files: true 
      - name: Copy Files for Artifact Upload
        run: rsync -av --exclude='build' --exclude={'src/'} ./. ./build
        working-directory: './'
      - name: Upload artifact 2
        uses: actions/upload-artifact@v4
        with:
          name: infrastructure2
          path: './'
          include-hidden-files: true   
      - name: show github workspace files 
        run: |
          ls ${{$github_workspace}} 
      - name: show current path files 
        run: |
          ls

      - name: Download Artifact 1
        uses: actions/download-artifact@v4
        with:
          name: infrastructure1
      - name: show current path files 
        run: |
          ls
      - name: Download Artifact 1
        uses: actions/download-artifact@v4
        with:
          name: infrastructure2
      - name: show current path files 
        run: |
          ls
      - name: Check out repository
        uses: actions/checkout@v4
      - name: show github workspace files 
        run: |
          ls ${{$github_workspace}} 
      - name: show current path files 
        run: |
          ls
                      


          
